package JFrame;

import java.util.HashSet;
import javax.swing.JOptionPane;
import trabajopracticon4.Alumno;
import trabajopracticon4.Colegio;
import trabajopracticon4.Materia;

public class InterInscripcion extends javax.swing.JInternalFrame {

    private HashSet<String> inscripcion = new HashSet();

    public InterInscripcion() {
        initComponents();
        this.setSize(400, 300);
        this.setTitle("Colegio");
        //Estos 2 forEach hacen que se carguen los comboBox
        for (Alumno alumno : Colegio.getListaAlumnos()) {
            jCBAlumno.addItem(alumno.toString());
        }
        for (Materia materia : Colegio.getListaMaterias()) {
            jCBMateria.addItem(materia.toString());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCBAlumno = new javax.swing.JComboBox<>();
        jCBMateria = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, -1, -1));

        jButton2.setText("Inscribir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Elija un alumno");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Elija una materia");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Formulario de Inscripcion");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        getContentPane().add(jCBAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 170, 30));

        getContentPane().add(jCBMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 170, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String aux = jCBAlumno.getSelectedItem() + "" + jCBMateria.getSelectedItem();
        if (Colegio.getIncripcion().contains(aux)) {
            JOptionPane.showMessageDialog(this, "El alumno ya esta incripto a la materia");

        } else {
            JOptionPane.showMessageDialog(this, "Alumno: " + jCBAlumno.getSelectedItem() + "\n se a incripto a " + jCBMateria.getSelectedItem());
            Colegio.getIncripcion().add(aux);
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jCBAlumno;
    private javax.swing.JComboBox<String> jCBMateria;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

}
