package JFrame;

import java.util.HashSet;
import java.util.Locale;
import javax.swing.JFrame;
import trabajopracticon4.Alumno;
import trabajopracticon4.Materia;

public class Menu extends javax.swing.JFrame {

    HashSet<Alumno> listaAlumnosMenu = new HashSet<>();
    HashSet<Materia> listaMateriaMenu = new HashSet<>();

    public Menu() {
        initComponents();
        this.setSize(600, 500);
        this.setLocationRelativeTo(null);
        this.setTitle("Menu");
        this.setResizable(false);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDPMEscritorio = new javax.swing.JDesktopPane();
        jMBMenu = new javax.swing.JMenuBar();
        JMAlumno = new javax.swing.JMenu();
        JMIalumno = new javax.swing.JMenuItem();
        JMmateria = new javax.swing.JMenu();
        jMImateria = new javax.swing.JMenuItem();
        JMinscripciones = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jDPMEscritorioLayout = new javax.swing.GroupLayout(jDPMEscritorio);
        jDPMEscritorio.setLayout(jDPMEscritorioLayout);
        jDPMEscritorioLayout.setHorizontalGroup(
            jDPMEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jDPMEscritorioLayout.setVerticalGroup(
            jDPMEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        getContentPane().add(jDPMEscritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 480));

        JMAlumno.setText("Alumnos");

        JMIalumno.setText("Formulario de Alumno");
        JMIalumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIalumnoActionPerformed(evt);
            }
        });
        JMAlumno.add(JMIalumno);

        jMBMenu.add(JMAlumno);

        JMmateria.setText("Materias");

        jMImateria.setText("Formulario de Materias");
        jMImateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMImateriaActionPerformed(evt);
            }
        });
        JMmateria.add(jMImateria);

        jMBMenu.add(JMmateria);

        JMinscripciones.setText("Inscripciones");

        jMenuItem3.setText("Formulario de Inscripcion");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        JMinscripciones.add(jMenuItem3);

        jMBMenu.add(JMinscripciones);

        setJMenuBar(jMBMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        jDPMEscritorio.removeAll();
        jDPMEscritorio.repaint();
        InterInscripcion interInscripcion = new InterInscripcion();
        jDPMEscritorio.add(interInscripcion);
        interInscripcion.setVisible(true);

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void JMIalumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIalumnoActionPerformed
        jDPMEscritorio.removeAll();
        jDPMEscritorio.repaint();
        InterAlumno interAlumno = new InterAlumno(listaAlumnosMenu);
        jDPMEscritorio.add(interAlumno);
        interAlumno.setVisible(true);

    }//GEN-LAST:event_JMIalumnoActionPerformed

    private void jMImateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMImateriaActionPerformed
        jDPMEscritorio.removeAll();
        jDPMEscritorio.repaint();
        InterMateria interMateria = new InterMateria(listaMateriaMenu);
        jDPMEscritorio.add(interMateria);
        interMateria.setVisible(true);

    }//GEN-LAST:event_jMImateriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMAlumno;
    private javax.swing.JMenuItem JMIalumno;
    private javax.swing.JMenu JMinscripciones;
    private javax.swing.JMenu JMmateria;
    private javax.swing.JDesktopPane jDPMEscritorio;
    private javax.swing.JMenuBar jMBMenu;
    private javax.swing.JMenuItem jMImateria;
    private javax.swing.JMenuItem jMenuItem3;
    // End of variables declaration//GEN-END:variables
    public void obtenerAlumnos(HashSet<Alumno> listaAlumnos) {

        for (Alumno alumno : listaAlumnos) {
            listaAlumnosMenu.add(alumno);
        }

    }
    public void obtenerMateria(HashSet<Materia> listaMaterias) {

        for (Materia materia : listaMaterias) {
            listaMateriaMenu.add(materia);
        }

    }
}
